### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by alanneves** [padcom/minimal-vue2-module-federation-example#1]
Is it possible to create a micro frontend app with a vue 2 app as host and the other packages being vue 3 apps?

**Comment by padcom** [comment]
Yes and no. The module federation mechanism gives you the capability to use remote modules (ECMAScript modules to be exact). So no, you can't just use a Vue 3.x component and shove it into a Vue 2.x because the API of Vue 2.x is not compatible with Vue 3.x.

However,...

There is nothing standing in your way to instantiate a new Vue application (regardless if it is Vue 2.x or Vue 3.x) and mount the component there. That way, you'll have an application within another application. It's perfectly normal and works without problems (just like using non-Vue libs in a Vue component). Just remember to start the application in `mounted()` and to destroy it in `beforeDestroy()` or it's 3.x equivalent.

Using this approach, you can use _any_ framework, including but not limited to: Angular, React and Svelte.
